name: "CI"

on: [push, workflow_dispatch]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USERNAME: ${{ github.actor }}
  JAVA_TOOL_OPTIONS: -Xmx5120m
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dkotlin.compiler.execution.strategy=in-process

jobs:

  validation:
    # Skip if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gradle Wrapper validation
        uses: gradle/wrapper-validation-action@v1

  build:
    # Skip if tags
    if: startsWith(github.ref , 'refs/tags/') != true
    name: "Build"
    runs-on: ubuntu-latest
    needs: validation

    steps:
      - uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build App
        # Build all
        run: ./gradlew -S assembleRelease

      - name: Copy Apk to Modul
        # FIXME
        run: |
          cd modul
          mkdir -p 'system/product/overlay/Anuan'
          cp -f '../overlay/com.android.phone/build/outputs/apk/release/com.android.phone-release.apk' 'system/product/overlay/Anuan/Anuan.apk'

      - name: Upload Modul
        uses: actions/upload-artifact@v3
        with:
          name: anuan_modul
          path: modul
